export { default as NotFound } from "./NotFound";
export { default as Activate } from "./Activate";
export { default as Login } from "./Login";
export { default as Main } from "./Main";
export { default as DataTableExample } from "./DataTableExample";
export { default as CadastralDetails } from "./CadastralDetails";
export { default as Recovery } from "./Recovery";
export { default as Register } from "./Register";
export { default as Reset } from "./Reset";